---
- hosts: "{{ myhost }}" 
  become: true
  vars_prompt:
    - name: patchroll
      prompt: Please enter P to patch R rollback and n exit
      private: no

    - name: service_name
      prompt: please enter the service name which want to stop
      private: no
 
  roles: 
    - os-patching-role

